<div>
    {% if not is_index %}
        <div style="text-align:left;font-size:14px;">
<p style="text-align:center;color: #ccc;">-------------本文结束<i class="fa fa-paw"></i>感谢您的阅读-------------</p>
<p><b>我的传送门：</b><a href="https://www.sunhong.vip/">博客</a>、<a href="https://www.jianshu.com/u/60dc3c4c6c3d">简书</a>、<a href="https://github.com/EllaSunQwQ">GitHub</a></p>
        </div>
    {% endif %}
</div>